### ISSUE TITLE
[Suggestion] Make use of mutliple files.

### ISSUE THREAD

**Issue by Root3287** [micahsgilbert/1064A#1]
So far your C++ code looks like spaghetti C code. I highly suggest you make use of your headers (.h/.hpp) and your source file (.c/.cpp). Headers usually declares something exists, Sources files defines what they are. 

I also noticed that you're using global variables, which is not that bad but can cause some issues down the line. https://www.youtube.com/watch?v=j0_u26Vpb4w&t=2m

**Comment by micahsgilbert** [comment]
I'm using the global variables for config and will read up on using a separate namespace & header file for config.
